### ISSUE TITLE
--Latest option and cbz convert [enhancement]

### ISSUE THREAD

**Issue by east-mist** [Zehina/Webtoon-Downloader#1]
Could you please add a --latest tag option to download only the last available chapter?
Also would be great to add a "create .cbz" option.

I want to shedule the download process via task manager and the above options would help doing it effortlesly.

For example, [here](https://github.com/hurlenko/mloader) is available both of above mentioned options.

**Comment by Zehina** [comment]
@east-mist, I've added the ```--latest``` positional argument as requested. see ffb6839d7ba3a310811b97681e2d3a0bdaaaf881.
As for the archiving to ***'.cbz, .cbr, ...'*** feature, It will take more time to fully implement but should come very soon hopefully in the next release.

**Comment by east-mist** [comment]
> @east-mist, I've added the `--latest` positional argument as requested. see [ffb6839](https://github.com/Zehina/Webtoon-Downloader/commit/ffb6839d7ba3a310811b97681e2d3a0bdaaaf881). As for the archiving to _**'.cbz, .cbr, ...'**_ feature, It will take more time to fully implement but should come very soon hopefully in the next release.

Thank you for your hard work!

**Comment by Zehina** [comment]
It is now possible to save as `cbz` `--save-as cbz`
