### ISSUE TITLE
--dest downloading into seperate webtoon-folders

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [Zehina/Webtoon-Downloader#11]
Hello, 
I would like to request an option(maybe something like --createseperatefolder(--createsepfol)) so that when someone defines a destination with --dest it still downloads the webtoon into it's own folder like when not providing --dest. 
I think that would make it a lot more useful to people who set an alias for this program and want all their Webtoons downloaded into another folder,[edit:] but still have them each in their own folder.

**Comment by Zehina** [comment]
This has been fixed in `1.0.0`
