### ISSUE TITLE
aiohttp missing from requirements.txt in V1.0.0 branch

### ISSUE THREAD

**Issue by TheExistingOne** [Zehina/Webtoon-Downloader#16]
Hello there,
I just found a minor issue and wanted to let you know. utils.py needs aiohttp but it's not included in the requirements.txt. Quickly fixed with pip, but probably worth adding. There might also be other missed imports but I'm not sure.

**Comment by Zehina** [comment]
Ah yes thank you, that branch is still Work in Progress. Not planning on merging yet. I'll leave open to keep it in mind :) 

I suggess using the latest release, Unless you know what you are doing with that branch
