### ISSUE TITLE
not working idk why

### ISSUE THREAD

**Issue by tympanicblock61** [Zehina/Webtoon-Downloader#17]
py webtoon_downloader.py "https://www.webtoons.com/en/horror/ghost-teller/prologue/viewer?title_no=1307&episode_no=1"
![image](https://user-images.githubusercontent.com/99092380/207543030-dd66e8a3-e342-42d8-8b77-1006b0431b68.png)

**Comment by the-acc-is-ef** [comment]
@tympanicblock61 
The link you entered is incorrect.
This is the correct link.
`python webtoon_downloader.py "https://www.webtoons.com/en/horror/ghost-teller/list?title_no=1307"`

**Comment by Zehina** [comment]
Thank you @the-acc-is-ef  💯
