### ISSUE TITLE
I don't know why it can't download successfully.

### ISSUE THREAD

**Issue by leslie100791** [Zehina/Webtoon-Downloader#18]
The other webtoons were all downloaded successfully,but this link don't,why?
link-->  https://www.webtoons.com/zh-hant/heartwarming/meinanyuyelang/list?title_no=1486

![未命名](https://user-images.githubusercontent.com/88264590/217014796-53d26720-bf26-46e1-a0aa-368e127d4b78.png)

**Comment by Zehina** [comment]
I suggest not using the git bash terminal with this tool. Use Powershell / Windows Terminal or WSL. Still it should be fixed now in. https://github.com/Zehina/Webtoon-Downloader/commit/6459713671a7eae192298499789f7393c073de80 if you want to use git bash
