### ISSUE TITLE
Cannot download WEBTOONs with "challenge" in the URL

### ISSUE THREAD

**Issue by Corrupt-Specturion** [Zehina/Webtoon-Downloader#2]
For example, trying to download https://www.webtoons.com/en/slice-of-life/hyperfocus/list?title_no=3340 works fine, but trying to download https://www.webtoons.com/en/challenge/bittersweet-candy-bowl/list?title_no=552823 returns:
`Traceback (most recent call last):
  File "webtoon_downloader.py", line 410, in <module>
    main()
  File "webtoon_downloader.py", line 407, in main
    download_webtoon(series_url, args.start, args.end, args.dest, args.images_format, args.latest, args.seperate)
  File "webtoon_downloader.py", line 318, in download_webtoon
    series_title = get_series_title(soup)
  File "webtoon_downloader.py", line 122, in get_series_title
    return html.find('h1', class_='subj').text
AttributeError: 'NoneType' object has no attribute 'text'`.
I have escaped both URLs with quotes.

**Comment by Zehina** [comment]
Hi @Corrupt-Specturion, Thank for highlighting this issue, Series belonging to the challenge category have a different html layout than regular series. 
the issue has been fixed in 8f2cd4f0ee59dc9469248ac6c139e4b5b4a8ec4f. It shouldn't break now when handling these series.
