### ISSUE TITLE
I don't know why it can't download successfully.

### ISSUE THREAD

**Issue by jtesjh** [Zehina/Webtoon-Downloader#20]
D:\Program\mhxz\Webtoon-Downloader\src>python webtoon_downloader.py "https://www.webtoons.com/en/challenge/crawling-dreams/list?title_no=141539"
[21:02:06] WARNING  Creading Directory: Crawling_Dreams                                                                                                    webtoon_downloader.py:372
Downloading Crawling Dreams from https://www.webtoons.com/en/challenge/crawling-dreams/list?title_no=141539

Traceback (most recent call last):
  File "D:\Program\mhxz\Webtoon-Downloader\src\webtoon_downloader.py", line 448, in <module>
    main()
  File "D:\Program\mhxz\Webtoon-Downloader\src\webtoon_downloader.py", line 445, in main
    download_webtoon(series_url, args.start, args.end, args.dest, args.images_format, args.latest, separate)
  File "D:\Program\mhxz\Webtoon-Downloader\src\webtoon_downloader.py", line 383, in download_webtoon
    chapters_to_download = get_chapters_details(session, viewer_url, start_chapter, end_chapter)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program\mhxz\Webtoon-Downloader\src\webtoon_downloader.py", line 206, in get_chapters_details
    in enumerate(soup.find('div', class_='episode_cont').find_all('li'), start=1)]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'

D:\Program\mhxz\Webtoon-Downloader\src>py "https://www.webtoons.com/en/challenge/crawling-dreams/list?title_no=141539"
C:\Python\python.exe: can't open file 'D:\\Program\\mhxz\\Webtoon-Downloader\\src\\https:\\www.webtoons.com\\en\\challenge\\crawling-dreams\\list?title_no=141539': [Errno 22] Invalid argument

**Comment by autodistries** [comment]
I've got the same problem. Maybe they updated UI ?

**Comment by jtesjh** [comment]
> 我有同样的问题。 也许他们更新了用户界面？

I don't know why, but other webtoon manga can still be downloaded well (except for my network issues and I don't know which folder has missing images). At present, I have found my native language version to replace it, but there are advertisements that are not pure enough, lol

**Comment by Zehina** [comment]
Please try now using latest master or this version https://github.com/Zehina/Webtoon-Downloader/releases/tag/v0.7.1
