### ISSUE TITLE
Windows filename rules not followed

### ISSUE THREAD

**Issue by FredMSloniker** [Zehina/Webtoon-Downloader#23]
Webtoon Downloader doesn't understand that the filename rules for Windows are somewhat different than those for Linux. When I tried to download 'Batman: Wayne Family Adventures', it tried to create a directory name with a colon in it, which isn't valid in Windows. Attached is the resulting error text.

[error.txt](https://github.com/Zehina/Webtoon-Downloader/files/11995737/error.txt)

**Comment by Zehina** [comment]
Thank you for the issue, this commit should fix: https://github.com/Zehina/Webtoon-Downloader/commit/2988abeeea314b8e9609c3dacbdf40bbf06daaf4 :)
