### ISSUE TITLE
No longer able to download 

### ISSUE THREAD

**Issue by yinya-6650** [Zehina/Webtoon-Downloader#24]
Tried to download a couple series but was given the same error and traceback for each.
![image](https://github.com/Zehina/Webtoon-Downloader/assets/142061339/b881b6ba-ad7e-47c9-beaf-834ce5d9c2cd)

**Comment by Zehina** [comment]
Fixed in https://github.com/Zehina/Webtoon-Downloader/commit/02f2acc9d28313ef4aa5d74bd6aded7d8114481b

Pull latest changes or download release: https://github.com/Zehina/Webtoon-Downloader/releases/tag/0.7.2
