### ISSUE TITLE
Pip isn't found

### ISSUE THREAD

**Issue by Sara-Abo-Shousha** [Zehina/Webtoon-Downloader#25]
When Navigate to the webtoon then src using the cd command, then paste this "pip install -r requirements.txt " i get 'pip' is not recognized as an internal or external command,
operable program or batch file.
The previous steps worked fine

**Comment by Lefro1** [comment]
If you have a problem with pip that is outside of the scope of this repo.

Potentially helpful page: https://stackoverflow.com/questions/23708898/pip-is-not-recognized-as-an-internal-or-external-command

**Comment by Zehina** [comment]
Hope you solved this issue @Sara-Abo-Shousha :). Hope @Lefro1 answer helped you if you hadn't installed python
