### ISSUE TITLE
Strange error while trying to execute basic command

### ISSUE THREAD

**Issue by Qmeriaux** [Zehina/Webtoon-Downloader#34]
[12/20/23 00:24:10] ERROR    Couldn't find a tree     webtoon_downloader.py:842
                             builder with the                                  
                             features you requested:                           
                             lxml. Do you need to                              
                             install a parser                                  
                             library?                                          
                             ┌─ Traceback (most rec─┐                          
                             │ C:\Users\Qmeri\Pycha │                          
                             │ rmProjects\Webtoon-D │                          
                             │ ownloader\src\webtoo │                          
                             │ n_downloader.py:829  │                          
                             │ in main              │                          
                             │                      │                          
                             │   826 │   separate = │                          
                             │   827 │   exporter = │                          
                             │   828 │   try:       │                          
                             │ > 829 │   │   downlo │                          
                             │   830 │   │   │   se │                          
                             │   831 │   │   │   ar │                          
                             │   832 │   │   │   ar │                          
                             │                      │                          
                             │ C:\Users\Qmeri\Pycha │                          
                             │ rmProjects\Webtoon-D │                          
                             │ ownloader\src\webtoo │                          
                             │ n_downloader.py:688  │                          
                             │ in download_webtoon  │                          
                             │                      │                          
                             │   685 │   session.co │                          
                             │   686 │   session.co │                          
                             │   687 │   resp = ses │                          
                             │ > 688 │   soup = Bea │                          
                             │   689 │   viewer_url │                          
                             │   690 │   series_tit │                          
                             │   691 │   if not (de │                          
                             │                      │                          
                             │ C:\Users\Qmeri\AppDa │                          
                             │ ta\Local\Programs\Py │                          
                             │ thon\Python310\lib\s │                          
                             │ ite-packages\bs4\__i │                          
                             │ nit__.py:250 in      │                          
                             │ __init__             │                          
                             │                      │                          
                             │   247 │   │   │   │  │                          
                             │   248 │   │   │   bu │                          
                             │   249 │   │   │   if │                          
                             │ > 250 │   │   │   │  │                          
                             │   251 │   │   │   │  │                          
                             │   252 │   │   │   │  │                          
                             │   253 │   │   │   │  │                          
                             └──────────────────────┘                          
                             FeatureNotFound:                                  
                             Couldn't find a tree                              
                             builder with the                                  
                             features you requested:                           
                             lxml. Do you need to                              
                             install a parser                                  
                             library?

**Comment by Zehina** [comment]
@Qmeriaux How did you install/run the script ? `lxml` is probalby not installed in your environment
