### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by L34RZ4** [Zehina/Webtoon-Downloader#38]
![Webtoon Downloader error](https://github.com/Zehina/Webtoon-Downloader/assets/121036226/e215370d-2d81-46d9-9ee2-52b8f8d2db25)

Followed the step by step but still getting errors, please help. 

Thanks in advance.

**Comment by L34RZ4** [comment]
Sorry, I forgot there was two  $ and removed one and it worked, thanks.

**Comment by Zehina** [comment]
@L34RZ4 It's fine. Also regarding PDF, I am currently adding that in the next release. It is working on my branch https://github.com/Zehina/Webtoon-Downloader/pull/36/files#diff-6b17e3aa7544a9a58af61089a7941593d3d15b177f02d6436acf5dcb0c9409bd and it should be coming out very very soon
