### ISSUE TITLE
Something, probably the latest release, has broken all WEBTOON downloading.

### ISSUE THREAD

**Issue by Corrupt-Specturion** [Zehina/Webtoon-Downloader#4]
`Traceback (most recent call last):
  File "webtoon_downloader.py", line 169, in <module>
    def get_chapters_details(session: requests.session, viewer_url: str, start_chapter: int = 1, end_chapter: int = None) -> list[ChapterInfo]:
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "webtoon_downloader.py", line 169, in <module>
    def get_chapters_details(session: requests.session, viewer_url: str, start_chapter: int = 1, end_chapter: int = None) -> list[ChapterInfo]:
TypeError: 'type' object is not subscriptable`

I've made sure the requirements are properly satisfied.

**Comment by Zehina** [comment]
Are you using an older version of Python (i.e Python ≤ 3.6.x)  ?
The project was never meant to support Python 3.6.x though yes the issue can be fixed by removing type hinting of the return function. Not all other functionalities are being tested on this specific version.

**Comment by Corrupt-Specturion** [comment]
![image](https://user-images.githubusercontent.com/54480005/153267374-85f332db-967f-4ab8-af96-20f2c7d41d79.png)

**Comment by Corrupt-Specturion** [comment]
It worked fine before the latest release. I'm thinking one of the commits after you fixed the challenge downloading messed it up.

**Comment by Zehina** [comment]
@Corrupt-Specturion Thank you, I've manager to fix it in 6c9d95933642672d3f3845d06bcfdb4a3b553933. 
It Should not break now, let me know if all your cases work as intended know using the latest release.

**Comment by Corrupt-Specturion** [comment]
It works fine now, thanks.
