### ISSUE TITLE
Why the "AttributeError: 'NoneType' object has no attribute 'split'" Error?

### ISSUE THREAD

**Issue by Shararehsalehi** [Zehina/Webtoon-Downloader#49]
I tried using it and everything went fine but after using the prompt " webtoon-downloader [https://www.webtoons.com/en/fantasy/1hp-club/list?title_no=2960]" I received "AttributeError: 'NoneType' object has no attribute 'split" error. What's wrong?

**Comment by Zehina** [comment]
Remove the brackets characters when passing the url. The command should be:
```
webtoon-downloader https://www.webtoons.com/en/fantasy/1hp-club/list?title_no=2960
```
