### ISSUE TITLE
Error: Chapter Name is causing error in file naming due to usage of restricted symbols

### ISSUE THREAD

**Issue by foxtbirdy** [Zehina/Webtoon-Downloader#50]
This will create an issue where the chapter names may create an error if the `--out` argument is used.
This is what happened in downloading dungeons and artifacts
The chapter name is What's a Goblin's Favorite Type of Fish?
![image](https://github.com/Zehina/Webtoon-Downloader/assets/72243209/2cffc1c4-cde0-44fd-a5be-d420127712e2)
![image](https://github.com/Zehina/Webtoon-Downloader/assets/72243209/9479a5c8-8e5e-4a5f-9ed5-46f6496dadba)

_Originally posted by @Code-Blender-7 in https://github.com/Zehina/Webtoon-Downloader/issues/3#issuecomment-2084200518_

**Comment by Code-Blender-7** [comment]
The folder naming is a useful tool. I recommend replacing string characters with whitespace to solve this issue and maintain the functionality with minor limitations.

**Comment by kikunayar** [comment]
https://github.com/Zehina/Webtoon-Downloader/issues/57

**Comment by stemalomd** [comment]
The issue is located in the chapter_directory variable on line 78 of webtoon_downloader\core\webtoon\downloaders\chapter.py. We need to replace any illegal characters in the chapter_directory, which represents the chapter directory name.
