### ISSUE TITLE
Add a delay between requests

### ISSUE THREAD

**Issue by YaBoiMax** [Zehina/Webtoon-Downloader#51]
**Is your feature request related to a problem? Please describe.**

Connections get closed because the tool spams the API with requests

**Describe the solution you would like**

a simple delay to simulate human behavior

**Comment by Zehina** [comment]
I added two new options to set the number of concurrent chapter/image downloads in order to deal with the rate limiting. See https://github.com/Zehina/Webtoon-Downloader/commit/0758b3c767f964e7d8cb63275e2b21bf35935b74
