### ISSUE TITLE
Download as PDF

### ISSUE THREAD

**Issue by L34RZ4** [Zehina/Webtoon-Downloader#53]
Greetings Zehina,

Just wanna say your program works like wonder.

Would like to know if there is a way to download the file as PDF instead of image?

Thanks in advance.

**Comment by L34RZ4** [comment]
Never Mind @Zehina, I read the help section and there is a way to download the file as pdf.

Thank you so much for your program and your hard work putting this together.

Cheers to you!

**Comment by Zehina** [comment]
Glad you enjoy using it. Closing
