### ISSUE TITLE
--proxy

### ISSUE THREAD

**Issue by CoCuCoH41k** [Zehina/Webtoon-Downloader#55]
**Is your feature request related to a problem? Please describe.**

I live in russian, and sometimes "Roskomnadzor" blocks sites. Webtoon are blocked for no reason. How do i download chapters?

**Describe the solution you would like**

add "--proxy [optional proxy adress]", if there is no connection, WD tries to use some proxy adresses or using ur own adress.

**Additional context**

I hate living in russia cause' "Roskomnadzor" does more crazy.

**Comment by Zehina** [comment]
I added the ability to use --proxy in https://github.com/Zehina/Webtoon-Downloader/commit/e965330c066044a6b6a4f849caf3de74c6388ed2
