### ISSUE TITLE
How can this software load images so quickly?

### ISSUE THREAD

**Issue by kikunayar** [Zehina/Webtoon-Downloader#58]
It took about 1 minute to load a total of 1.30 GB of files. Normally, it takes me more than 10 minutes to load a game on Steam this size.

**Comment by Zehina** [comment]
There's several factors at play such as your ISP, The server you're downloading from, etc... But I don't think it should be that much of a difference _(10x)_. The main limiting factor in the example of downloading from Webtoon vs Steam servers would be your Bandwidth.
