### ISSUE TITLE
Incorrect File Extenstions

### ISSUE THREAD

**Issue by johninaba** [Zehina/Webtoon-Downloader#8]
Occasionally the downloaded images have the incorrect extension . PNG instead of JPEG for example.

**Comment by Zehina** [comment]
Could you provide the options you provided when running the script ?

**Comment by johninaba** [comment]
-d was the only option I used.

**Comment by Zehina** [comment]
What's the entire command you used. Webtoon url and options.

**Comment by johninaba** [comment]
python webtoon_downloader.py -d d:\test https://www.webtoons.com/en/romance/lore-olympus/list?title_no=1320

**Comment by Zehina** [comment]
This is due, to the project assuming that all images are `JPEG` by default, since that's what they `normally` use. But I guess this should be changed to actually convert images that are downloaded as `PNG` to `JPEG`.

**Comment by johninaba** [comment]
Maybe add file type detection as well with an option to keep the original format. I've just been renaming with IrfanView in the interim.

**Comment by Zehina** [comment]
This is now fixed in `1.0.0`. Images should be properly converted depending on the provided image extension
