### ISSUE TITLE
Pad filenames with leading zeroes?

### ISSUE THREAD

**Issue by Mrifk** [Zehina/Webtoon-Downloader#9]
Would be nice to have an option to pad file/directory names with leading zeroes, so instead of a directory listing that goes:

1 10 100 101 102 103 104 105 106 107 108 109 11 110 (etc.)

instead it would produce a listing that goes

001 002 003 004 005 006 007 008 009 010 011 012 (etc.)

**Comment by celia-v** [comment]
@Zehina this could be accomplished by first taking the argument `end_chapter` from function `download_webtoon`, calculating `zeros = int(math.log10(end_chapter))+1` then passing it to `download_chapter` and then to `download_image` where you can use it in the `file_name` like this `file_name = f'{chapter_number:0{zeros}d}_{page_number}'`
